name: Daily Wix Import

on:
  schedule:
    - cron: '17 4 * * *'  # daily at 04:17 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -V
          # No external deps; stdlib only
      
      - name: Export posts (markdown with inline media & docs)
        env:
          SOURCE_URL: ${{ vars.SOURCE_URL }}
          DOC_URL_HINTS: ${{ vars.DOC_URL_HINTS }}
        run: |
          python scripts/export_wix_blog_to_md.py \
            --out-dir content/posts \
            --structure year/slug \
            --scrape \
            --body-format markdown \
            --download-inline-images

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          commit_msg="chore(export): update posts $(date -u +'%Y-%m-%d %H:%M:%SZ')"
          git commit -m "$commit_msg"
          git push
